### ISSUE TITLE
How to override require and require.resolve?

### ISSUE THREAD

**Issue by stevefan1999-personal** [neonious/lowjs#11]
Following up on https://github.com/neonious/lowjs/issues/9, I have successfully used an alternative implementation of `require.resolve `, yet from my experiments it is realized that the commonjs objects are actually immutable, making it impossible to rewrite their reference globally.

```js
require.resolve = function(x) {
  return __require("resolve").sync(x, { preserveSymlinks: true });
};

__require = require;
require = new Proxy(require, {
  apply: function(target, thisArg, argumentsList) {
    return __require.apply(thisArg, argumentsList.map(require.resolve));
  }
});

// Actually require is distinct for each module!
```

I'm doing it on request of trying to use `node_modules` and starting to test low.js with standard node.js test suite.

**Comment by neoniousTR** [comment]
- Thank you for working on the stats items! Will merge your pull request in the next days

- To test low.js with the standard node.js test suite, check https://github.com/neonious/lowjs/tree/master/test

- Is it normally important for require not be distinct for each module? Not sure if we should work on changing that, because I started implementing that low.js checks all paths for all modules just like Node.JS from inside the C++ low_modules.cpp. I'd by happy to try to finish it till end of this weekend (end of 7th Oct) and commit it.. Will definitly be faster than the resolve written in JS

But I am sure it was a fun project (and/or hard work) trying to get the alternative resolve to work.., seems like you are/were almost there !

**Comment by nyteshade** [comment]
Waiting for either solution to come to fruition. 

![Waiting on bated breath](https://i.pinimg.com/originals/99/48/78/994878bd7cbda297e7b529827d358f7f.gif)

**Comment by neoniousTR** [comment]
Developed, and testing. Trying to push till Tuesday.

Von meinem iPhone gesendet
