### ISSUE TITLE
SyntaxError: unterminated statement (line 7)

### ISSUE THREAD

**Issue by atmoner** [neonious/lowjs#126]
Hello,
The first compilation is going correctly, the example works but when I send a new scetch, I constantly have this error:

![image](https://user-images.githubusercontent.com/1071490/106063061-8c2ad680-60ef-11eb-8fb5-ba2aeb804c02.png)

and the client becomes unreachable :/

**Comment by ThomasRogg** [comment]
This is because you turned transplation off. low.js only supports ES5.1. So keywords like let do not work.

I just deployed lowsync 1.4.10. Can you check whether that version works with transpilation but without the invariant not found message? Might, but might not, as I am tapping in the dark: I cannot reproduce your problem on my own computer (Mac)..

Thomas

**Comment by atmoner** [comment]
> This is because you turned transplation off. low.js only supports ES5.1. So keywords like let do not work.
> 
> I just deployed lowsync 1.4.10. Can you check whether that version works with transpilation but without the invariant not found message? Might, but might not, as I am tapping in the dark: I cannot reproduce your problem on my own computer (Mac)..
> 
> Thomas

Hello Thomas,
indeed, I had to adapt to understand the problem by deactivating the transplation...
I updated lowsync to version 1.4.10, I activated the transplation, I uploaded a new js code and finally, it works great :+1: 

Thank you very much for fixing my problem.
