### ISSUE TITLE
I would suggest setting up builds using. dockcross

### ISSUE THREAD

**Issue by windbender** [neonious/lowjs#13]
https://github.com/dockcross/dockcross

**Comment by neoniousTR** [comment]
We are currently linking statically to musl to not have dependencies to glibc (which creates problems when using old linux systems) and still have a small binary size. Because of this, the Linux binaries are currently built under Alpine Linux systems.

Dockcross does not use musl, am I correct?

So Dockcross is not an option for now, sorry.
