### ISSUE TITLE
Close  method returns only 'true'

### ISSUE THREAD

**Issue by janus** [neonious/lowjs#19]
I can't figure out how this method would return false.
``
bool LowFile::Close(int callIndex)
{
    if (mClose)
    {
        duk_dup(mLow->duk_ctx, callIndex);
        low_push_error(mLow, EBADF, "close");
        duk_call(mLow->duk_ctx, 1);
        return true;
    }
    if (mPhase != LOWFILE_PHASE_READY)
    {
        duk_dup(mLow->duk_ctx, callIndex);
        low_push_error(mLow, EALREADY, "close");
        duk_call(mLow->duk_ctx, 1);
        return true;
    }
    // We must no longer advertise, so we do not remove other persons FD later on
    int fd = FD();
    SetFD(-1);
    AdvertiseFD();
    SetFD(fd);

    if (callIndex != -1)
    {
        mCallID = low_add_stash(mLow, callIndex);
        if (mCallID)
            mLow->run_ref++;
    }
    else
        mCallID = 0;

    mPhase = LOWFILE_PHASE_CLOSING;
    mDataDone = false;
    low_data_set_callback(mLow, this, LOW_DATA_THREAD_PRIORITY_READ);

    return true;
}
``

**Comment by neoniousTR** [comment]
Close() is a virtual method from LowFD. And other implementations might return false, in which case the LowFD is deleted.

I'm not a fan on how I wrote this... There are some things you have to watch out when using LowLoopCallback, LowDataCallback or LowFD so that there is no deadlock especially when getting rid of stuff... But I verified all paths, everything should work the way it is.

So, not changing this single thing, rather I'd rewrite the whole mechanism sometime in the future.
